// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameProject = "project"

// Project mapped from table <project>
type Project struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name       string    `gorm:"column:name;not null" json:"name"`
	Key        string    `gorm:"column:key;not null" json:"key"`
	ServerKey  string    `gorm:"column:server_key;not null" json:"server_key"`
	ClientKey  string    `gorm:"column:client_key;not null" json:"client_key"`
	CreateTime time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
}

// TableName Project's table name
func (*Project) TableName() string {
	return TableNameProject
}
