// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameReqGroup = "req_group"

// ReqGroup mapped from table <req_group>
type ReqGroup struct {
	GroupID     int64     `gorm:"column:group_id;primaryKey;autoIncrement:true" json:"group_id"`
	Title       string    `gorm:"column:title;not null" json:"title"`
	Key         string    `gorm:"column:key;not null" json:"key"`
	Description string    `gorm:"column:description;not null" json:"description"`
	CreateTime  time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime  time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
}

// TableName ReqGroup's table name
func (*ReqGroup) TableName() string {
	return TableNameReqGroup
}
