// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameToggleRuleValue = "toggle_rule_value"

// ToggleRuleValue mapped from table <toggle_rule_value>
type ToggleRuleValue struct {
	ID           int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ToggleRuleID int64     `gorm:"column:toggle_rule_id;not null" json:"toggle_rule_id"`
	ValueID      int64     `gorm:"column:value_id;not null" json:"value_id"`
	Percentage   int32     `gorm:"column:percentage;not null" json:"percentage"`
	CreateTime   time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
}

// TableName ToggleRuleValue's table name
func (*ToggleRuleValue) TableName() string {
	return TableNameToggleRuleValue
}
