// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.27.0
// source: common/protobuf/toggle.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BoolToggleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReqUser      *ReqUser `protobuf:"bytes,1,opt,name=reqUser,proto3" json:"reqUser,omitempty"`
	ProjectKey   string   `protobuf:"bytes,2,opt,name=projectKey,proto3" json:"projectKey,omitempty"`
	ToggleKey    string   `protobuf:"bytes,3,opt,name=toggleKey,proto3" json:"toggleKey,omitempty"`
	DefaultValue bool     `protobuf:"varint,4,opt,name=defaultValue,proto3" json:"defaultValue,omitempty"`
}

func (x *BoolToggleRequest) Reset() {
	*x = BoolToggleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_protobuf_toggle_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BoolToggleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoolToggleRequest) ProtoMessage() {}

func (x *BoolToggleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_protobuf_toggle_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoolToggleRequest.ProtoReflect.Descriptor instead.
func (*BoolToggleRequest) Descriptor() ([]byte, []int) {
	return file_common_protobuf_toggle_proto_rawDescGZIP(), []int{0}
}

func (x *BoolToggleRequest) GetReqUser() *ReqUser {
	if x != nil {
		return x.ReqUser
	}
	return nil
}

func (x *BoolToggleRequest) GetProjectKey() string {
	if x != nil {
		return x.ProjectKey
	}
	return ""
}

func (x *BoolToggleRequest) GetToggleKey() string {
	if x != nil {
		return x.ToggleKey
	}
	return ""
}

func (x *BoolToggleRequest) GetDefaultValue() bool {
	if x != nil {
		return x.DefaultValue
	}
	return false
}

type BoolToggleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ToggleKey   string `protobuf:"bytes,1,opt,name=toggleKey,proto3" json:"toggleKey,omitempty"`
	ResultValue bool   `protobuf:"varint,2,opt,name=resultValue,proto3" json:"resultValue,omitempty"`
}

func (x *BoolToggleResponse) Reset() {
	*x = BoolToggleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_protobuf_toggle_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BoolToggleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoolToggleResponse) ProtoMessage() {}

func (x *BoolToggleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_protobuf_toggle_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoolToggleResponse.ProtoReflect.Descriptor instead.
func (*BoolToggleResponse) Descriptor() ([]byte, []int) {
	return file_common_protobuf_toggle_proto_rawDescGZIP(), []int{1}
}

func (x *BoolToggleResponse) GetToggleKey() string {
	if x != nil {
		return x.ToggleKey
	}
	return ""
}

func (x *BoolToggleResponse) GetResultValue() bool {
	if x != nil {
		return x.ResultValue
	}
	return false
}

type StringToggleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReqUser      *ReqUser `protobuf:"bytes,1,opt,name=reqUser,proto3" json:"reqUser,omitempty"`
	ProjectKey   string   `protobuf:"bytes,2,opt,name=projectKey,proto3" json:"projectKey,omitempty"`
	ToggleKey    string   `protobuf:"bytes,3,opt,name=toggleKey,proto3" json:"toggleKey,omitempty"`
	DefaultValue string   `protobuf:"bytes,4,opt,name=defaultValue,proto3" json:"defaultValue,omitempty"`
}

func (x *StringToggleRequest) Reset() {
	*x = StringToggleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_protobuf_toggle_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StringToggleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringToggleRequest) ProtoMessage() {}

func (x *StringToggleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_protobuf_toggle_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringToggleRequest.ProtoReflect.Descriptor instead.
func (*StringToggleRequest) Descriptor() ([]byte, []int) {
	return file_common_protobuf_toggle_proto_rawDescGZIP(), []int{2}
}

func (x *StringToggleRequest) GetReqUser() *ReqUser {
	if x != nil {
		return x.ReqUser
	}
	return nil
}

func (x *StringToggleRequest) GetProjectKey() string {
	if x != nil {
		return x.ProjectKey
	}
	return ""
}

func (x *StringToggleRequest) GetToggleKey() string {
	if x != nil {
		return x.ToggleKey
	}
	return ""
}

func (x *StringToggleRequest) GetDefaultValue() string {
	if x != nil {
		return x.DefaultValue
	}
	return ""
}

type StringToggleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ToggleKey   string `protobuf:"bytes,1,opt,name=toggleKey,proto3" json:"toggleKey,omitempty"`
	ResultValue string `protobuf:"bytes,2,opt,name=resultValue,proto3" json:"resultValue,omitempty"`
}

func (x *StringToggleResponse) Reset() {
	*x = StringToggleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_protobuf_toggle_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StringToggleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringToggleResponse) ProtoMessage() {}

func (x *StringToggleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_protobuf_toggle_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringToggleResponse.ProtoReflect.Descriptor instead.
func (*StringToggleResponse) Descriptor() ([]byte, []int) {
	return file_common_protobuf_toggle_proto_rawDescGZIP(), []int{3}
}

func (x *StringToggleResponse) GetToggleKey() string {
	if x != nil {
		return x.ToggleKey
	}
	return ""
}

func (x *StringToggleResponse) GetResultValue() string {
	if x != nil {
		return x.ResultValue
	}
	return ""
}

type FloatToggleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReqUser      *ReqUser `protobuf:"bytes,1,opt,name=reqUser,proto3" json:"reqUser,omitempty"`
	ProjectKey   string   `protobuf:"bytes,2,opt,name=projectKey,proto3" json:"projectKey,omitempty"`
	ToggleKey    string   `protobuf:"bytes,3,opt,name=toggleKey,proto3" json:"toggleKey,omitempty"`
	DefaultValue float32  `protobuf:"fixed32,4,opt,name=defaultValue,proto3" json:"defaultValue,omitempty"`
}

func (x *FloatToggleRequest) Reset() {
	*x = FloatToggleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_protobuf_toggle_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FloatToggleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FloatToggleRequest) ProtoMessage() {}

func (x *FloatToggleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_protobuf_toggle_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FloatToggleRequest.ProtoReflect.Descriptor instead.
func (*FloatToggleRequest) Descriptor() ([]byte, []int) {
	return file_common_protobuf_toggle_proto_rawDescGZIP(), []int{4}
}

func (x *FloatToggleRequest) GetReqUser() *ReqUser {
	if x != nil {
		return x.ReqUser
	}
	return nil
}

func (x *FloatToggleRequest) GetProjectKey() string {
	if x != nil {
		return x.ProjectKey
	}
	return ""
}

func (x *FloatToggleRequest) GetToggleKey() string {
	if x != nil {
		return x.ToggleKey
	}
	return ""
}

func (x *FloatToggleRequest) GetDefaultValue() float32 {
	if x != nil {
		return x.DefaultValue
	}
	return 0
}

type FloatToggleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ToggleKey   string  `protobuf:"bytes,1,opt,name=toggleKey,proto3" json:"toggleKey,omitempty"`
	ResultValue float32 `protobuf:"fixed32,2,opt,name=resultValue,proto3" json:"resultValue,omitempty"`
}

func (x *FloatToggleResponse) Reset() {
	*x = FloatToggleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_protobuf_toggle_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FloatToggleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FloatToggleResponse) ProtoMessage() {}

func (x *FloatToggleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_protobuf_toggle_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FloatToggleResponse.ProtoReflect.Descriptor instead.
func (*FloatToggleResponse) Descriptor() ([]byte, []int) {
	return file_common_protobuf_toggle_proto_rawDescGZIP(), []int{5}
}

func (x *FloatToggleResponse) GetToggleKey() string {
	if x != nil {
		return x.ToggleKey
	}
	return ""
}

func (x *FloatToggleResponse) GetResultValue() float32 {
	if x != nil {
		return x.ResultValue
	}
	return 0
}

type IntToggleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReqUser      *ReqUser `protobuf:"bytes,1,opt,name=reqUser,proto3" json:"reqUser,omitempty"`
	ProjectKey   string   `protobuf:"bytes,2,opt,name=projectKey,proto3" json:"projectKey,omitempty"`
	ToggleKey    string   `protobuf:"bytes,3,opt,name=toggleKey,proto3" json:"toggleKey,omitempty"`
	DefaultValue int64    `protobuf:"varint,4,opt,name=defaultValue,proto3" json:"defaultValue,omitempty"`
}

func (x *IntToggleRequest) Reset() {
	*x = IntToggleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_protobuf_toggle_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IntToggleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntToggleRequest) ProtoMessage() {}

func (x *IntToggleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_protobuf_toggle_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntToggleRequest.ProtoReflect.Descriptor instead.
func (*IntToggleRequest) Descriptor() ([]byte, []int) {
	return file_common_protobuf_toggle_proto_rawDescGZIP(), []int{6}
}

func (x *IntToggleRequest) GetReqUser() *ReqUser {
	if x != nil {
		return x.ReqUser
	}
	return nil
}

func (x *IntToggleRequest) GetProjectKey() string {
	if x != nil {
		return x.ProjectKey
	}
	return ""
}

func (x *IntToggleRequest) GetToggleKey() string {
	if x != nil {
		return x.ToggleKey
	}
	return ""
}

func (x *IntToggleRequest) GetDefaultValue() int64 {
	if x != nil {
		return x.DefaultValue
	}
	return 0
}

type IntToggleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ToggleKey   string `protobuf:"bytes,1,opt,name=toggleKey,proto3" json:"toggleKey,omitempty"`
	ResultValue int64  `protobuf:"varint,2,opt,name=resultValue,proto3" json:"resultValue,omitempty"`
}

func (x *IntToggleResponse) Reset() {
	*x = IntToggleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_protobuf_toggle_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IntToggleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntToggleResponse) ProtoMessage() {}

func (x *IntToggleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_protobuf_toggle_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntToggleResponse.ProtoReflect.Descriptor instead.
func (*IntToggleResponse) Descriptor() ([]byte, []int) {
	return file_common_protobuf_toggle_proto_rawDescGZIP(), []int{7}
}

func (x *IntToggleResponse) GetToggleKey() string {
	if x != nil {
		return x.ToggleKey
	}
	return ""
}

func (x *IntToggleResponse) GetResultValue() int64 {
	if x != nil {
		return x.ResultValue
	}
	return 0
}

type JsonToggleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReqUser      *ReqUser `protobuf:"bytes,1,opt,name=reqUser,proto3" json:"reqUser,omitempty"`
	ProjectKey   string   `protobuf:"bytes,2,opt,name=projectKey,proto3" json:"projectKey,omitempty"`
	ToggleKey    string   `protobuf:"bytes,3,opt,name=toggleKey,proto3" json:"toggleKey,omitempty"`
	DefaultValue string   `protobuf:"bytes,4,opt,name=defaultValue,proto3" json:"defaultValue,omitempty"`
}

func (x *JsonToggleRequest) Reset() {
	*x = JsonToggleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_protobuf_toggle_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JsonToggleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsonToggleRequest) ProtoMessage() {}

func (x *JsonToggleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_protobuf_toggle_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsonToggleRequest.ProtoReflect.Descriptor instead.
func (*JsonToggleRequest) Descriptor() ([]byte, []int) {
	return file_common_protobuf_toggle_proto_rawDescGZIP(), []int{8}
}

func (x *JsonToggleRequest) GetReqUser() *ReqUser {
	if x != nil {
		return x.ReqUser
	}
	return nil
}

func (x *JsonToggleRequest) GetProjectKey() string {
	if x != nil {
		return x.ProjectKey
	}
	return ""
}

func (x *JsonToggleRequest) GetToggleKey() string {
	if x != nil {
		return x.ToggleKey
	}
	return ""
}

func (x *JsonToggleRequest) GetDefaultValue() string {
	if x != nil {
		return x.DefaultValue
	}
	return ""
}

type JsonToggleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ToggleKey   string `protobuf:"bytes,1,opt,name=toggleKey,proto3" json:"toggleKey,omitempty"`
	ResultValue string `protobuf:"bytes,2,opt,name=resultValue,proto3" json:"resultValue,omitempty"`
}

func (x *JsonToggleResponse) Reset() {
	*x = JsonToggleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_protobuf_toggle_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JsonToggleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsonToggleResponse) ProtoMessage() {}

func (x *JsonToggleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_protobuf_toggle_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsonToggleResponse.ProtoReflect.Descriptor instead.
func (*JsonToggleResponse) Descriptor() ([]byte, []int) {
	return file_common_protobuf_toggle_proto_rawDescGZIP(), []int{9}
}

func (x *JsonToggleResponse) GetToggleKey() string {
	if x != nil {
		return x.ToggleKey
	}
	return ""
}

func (x *JsonToggleResponse) GetResultValue() string {
	if x != nil {
		return x.ResultValue
	}
	return ""
}

type ReqUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RolloutKey string            `protobuf:"bytes,1,opt,name=rolloutKey,proto3" json:"rolloutKey,omitempty"`
	Attributes map[string]string `protobuf:"bytes,2,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *ReqUser) Reset() {
	*x = ReqUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_protobuf_toggle_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqUser) ProtoMessage() {}

func (x *ReqUser) ProtoReflect() protoreflect.Message {
	mi := &file_common_protobuf_toggle_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqUser.ProtoReflect.Descriptor instead.
func (*ReqUser) Descriptor() ([]byte, []int) {
	return file_common_protobuf_toggle_proto_rawDescGZIP(), []int{10}
}

func (x *ReqUser) GetRolloutKey() string {
	if x != nil {
		return x.RolloutKey
	}
	return ""
}

func (x *ReqUser) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

var File_common_protobuf_toggle_proto protoreflect.FileDescriptor

var file_common_protobuf_toggle_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x74, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x99,
	0x01, 0x0a, 0x11, 0x42, 0x6f, 0x6f, 0x6c, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x55, 0x73, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x52, 0x65, 0x71, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x07, 0x72, 0x65, 0x71, 0x55, 0x73, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x6a,
	0x65, 0x63, 0x74, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72,
	0x6f, 0x6a, 0x65, 0x63, 0x74, 0x4b, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x6f, 0x67, 0x67,
	0x6c, 0x65, 0x4b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x6f, 0x67,
	0x67, 0x6c, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x22, 0x0a, 0x0c, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c,
	0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x64, 0x65,
	0x66, 0x61, 0x75, 0x6c, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x54, 0x0a, 0x12, 0x42, 0x6f,
	0x6f, 0x6c, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x74, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x20,
	0x0a, 0x0b, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0b, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x22, 0x9b, 0x01, 0x0a, 0x13, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x54, 0x6f, 0x67, 0x67, 0x6c,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x55,
	0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x52, 0x65, 0x71, 0x55,
	0x73, 0x65, 0x72, 0x52, 0x07, 0x72, 0x65, 0x71, 0x55, 0x73, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a,
	0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x4b, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x09,
	0x74, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x4b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x74, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x22, 0x0a, 0x0c, 0x64, 0x65,
	0x66, 0x61, 0x75, 0x6c, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x56,
	0x0a, 0x14, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x6f, 0x67, 0x67, 0x6c, 0x65,
	0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x6f, 0x67, 0x67, 0x6c,
	0x65, 0x4b, 0x65, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x9a, 0x01, 0x0a, 0x12, 0x46, 0x6c, 0x6f, 0x61, 0x74,
	0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a,
	0x07, 0x72, 0x65, 0x71, 0x55, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08,
	0x2e, 0x52, 0x65, 0x71, 0x55, 0x73, 0x65, 0x72, 0x52, 0x07, 0x72, 0x65, 0x71, 0x55, 0x73, 0x65,
	0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x4b, 0x65, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x4b, 0x65,
	0x79, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x4b, 0x65, 0x79, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x4b, 0x65, 0x79, 0x12,
	0x22, 0x0a, 0x0c, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0c, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x22, 0x55, 0x0a, 0x13, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x54, 0x6f, 0x67, 0x67,
	0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x6f,
	0x67, 0x67, 0x6c, 0x65, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74,
	0x6f, 0x67, 0x67, 0x6c, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0b, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x98, 0x01, 0x0a, 0x10, 0x49,
	0x6e, 0x74, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x22, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x55, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x08, 0x2e, 0x52, 0x65, 0x71, 0x55, 0x73, 0x65, 0x72, 0x52, 0x07, 0x72, 0x65, 0x71, 0x55,
	0x73, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x4b, 0x65,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74,
	0x4b, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x4b, 0x65, 0x79,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x4b, 0x65,
	0x79, 0x12, 0x22, 0x0a, 0x0c, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x53, 0x0a, 0x11, 0x49, 0x6e, 0x74, 0x54, 0x6f, 0x67, 0x67,
	0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x6f,
	0x67, 0x67, 0x6c, 0x65, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74,
	0x6f, 0x67, 0x67, 0x6c, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x99, 0x01, 0x0a, 0x11, 0x4a,
	0x73, 0x6f, 0x6e, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x22, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x55, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x08, 0x2e, 0x52, 0x65, 0x71, 0x55, 0x73, 0x65, 0x72, 0x52, 0x07, 0x72, 0x65, 0x71,
	0x55, 0x73, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x4b,
	0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63,
	0x74, 0x4b, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x4b, 0x65,
	0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x4b,
	0x65, 0x79, 0x12, 0x22, 0x0a, 0x0c, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c,
	0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x54, 0x0a, 0x12, 0x4a, 0x73, 0x6f, 0x6e, 0x54, 0x6f,
	0x67, 0x67, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09,
	0x74, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x74, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0xa2, 0x01, 0x0a,
	0x07, 0x52, 0x65, 0x71, 0x55, 0x73, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x6f, 0x6c, 0x6c,
	0x6f, 0x75, 0x74, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x6f,
	0x6c, 0x6c, 0x6f, 0x75, 0x74, 0x4b, 0x65, 0x79, 0x12, 0x38, 0x0a, 0x0a, 0x61, 0x74, 0x74, 0x72,
	0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x52,
	0x65, 0x71, 0x55, 0x73, 0x65, 0x72, 0x2e, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0a, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74,
	0x65, 0x73, 0x1a, 0x3d, 0x0a, 0x0f, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38,
	0x01, 0x32, 0xb7, 0x02, 0x0a, 0x0d, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x38, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x6f, 0x6c, 0x54, 0x6f,
	0x67, 0x67, 0x6c, 0x65, 0x12, 0x12, 0x2e, 0x42, 0x6f, 0x6f, 0x6c, 0x54, 0x6f, 0x67, 0x67, 0x6c,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x42, 0x6f, 0x6f, 0x6c, 0x54,
	0x6f, 0x67, 0x67, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a,
	0x0f, 0x47, 0x65, 0x74, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65,
	0x12, 0x14, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x54,
	0x6f, 0x67, 0x67, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a,
	0x0e, 0x47, 0x65, 0x74, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x12,
	0x13, 0x2e, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x54, 0x6f, 0x67, 0x67,
	0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x0c, 0x47, 0x65,
	0x74, 0x49, 0x6e, 0x74, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x12, 0x11, 0x2e, 0x49, 0x6e, 0x74,
	0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e,
	0x49, 0x6e, 0x74, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x38, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x4a, 0x73, 0x6f, 0x6e, 0x54, 0x6f, 0x67, 0x67,
	0x6c, 0x65, 0x12, 0x12, 0x2e, 0x4a, 0x73, 0x6f, 0x6e, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x4a, 0x73, 0x6f, 0x6e, 0x54, 0x6f, 0x67,
	0x67, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_common_protobuf_toggle_proto_rawDescOnce sync.Once
	file_common_protobuf_toggle_proto_rawDescData = file_common_protobuf_toggle_proto_rawDesc
)

func file_common_protobuf_toggle_proto_rawDescGZIP() []byte {
	file_common_protobuf_toggle_proto_rawDescOnce.Do(func() {
		file_common_protobuf_toggle_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_protobuf_toggle_proto_rawDescData)
	})
	return file_common_protobuf_toggle_proto_rawDescData
}

var file_common_protobuf_toggle_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_common_protobuf_toggle_proto_goTypes = []interface{}{
	(*BoolToggleRequest)(nil),    // 0: BoolToggleRequest
	(*BoolToggleResponse)(nil),   // 1: BoolToggleResponse
	(*StringToggleRequest)(nil),  // 2: StringToggleRequest
	(*StringToggleResponse)(nil), // 3: StringToggleResponse
	(*FloatToggleRequest)(nil),   // 4: FloatToggleRequest
	(*FloatToggleResponse)(nil),  // 5: FloatToggleResponse
	(*IntToggleRequest)(nil),     // 6: IntToggleRequest
	(*IntToggleResponse)(nil),    // 7: IntToggleResponse
	(*JsonToggleRequest)(nil),    // 8: JsonToggleRequest
	(*JsonToggleResponse)(nil),   // 9: JsonToggleResponse
	(*ReqUser)(nil),              // 10: ReqUser
	nil,                          // 11: ReqUser.AttributesEntry
}
var file_common_protobuf_toggle_proto_depIdxs = []int32{
	10, // 0: BoolToggleRequest.reqUser:type_name -> ReqUser
	10, // 1: StringToggleRequest.reqUser:type_name -> ReqUser
	10, // 2: FloatToggleRequest.reqUser:type_name -> ReqUser
	10, // 3: IntToggleRequest.reqUser:type_name -> ReqUser
	10, // 4: JsonToggleRequest.reqUser:type_name -> ReqUser
	11, // 5: ReqUser.attributes:type_name -> ReqUser.AttributesEntry
	0,  // 6: ToggleService.GetBoolToggle:input_type -> BoolToggleRequest
	2,  // 7: ToggleService.GetStringToggle:input_type -> StringToggleRequest
	4,  // 8: ToggleService.GetFloatToggle:input_type -> FloatToggleRequest
	6,  // 9: ToggleService.GetIntToggle:input_type -> IntToggleRequest
	8,  // 10: ToggleService.GetJsonToggle:input_type -> JsonToggleRequest
	1,  // 11: ToggleService.GetBoolToggle:output_type -> BoolToggleResponse
	3,  // 12: ToggleService.GetStringToggle:output_type -> StringToggleResponse
	5,  // 13: ToggleService.GetFloatToggle:output_type -> FloatToggleResponse
	7,  // 14: ToggleService.GetIntToggle:output_type -> IntToggleResponse
	9,  // 15: ToggleService.GetJsonToggle:output_type -> JsonToggleResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_common_protobuf_toggle_proto_init() }
func file_common_protobuf_toggle_proto_init() {
	if File_common_protobuf_toggle_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_protobuf_toggle_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BoolToggleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_protobuf_toggle_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BoolToggleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_protobuf_toggle_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StringToggleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_protobuf_toggle_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StringToggleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_protobuf_toggle_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FloatToggleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_protobuf_toggle_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FloatToggleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_protobuf_toggle_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IntToggleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_protobuf_toggle_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IntToggleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_protobuf_toggle_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JsonToggleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_protobuf_toggle_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JsonToggleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_protobuf_toggle_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_protobuf_toggle_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_common_protobuf_toggle_proto_goTypes,
		DependencyIndexes: file_common_protobuf_toggle_proto_depIdxs,
		MessageInfos:      file_common_protobuf_toggle_proto_msgTypes,
	}.Build()
	File_common_protobuf_toggle_proto = out.File
	file_common_protobuf_toggle_proto_rawDesc = nil
	file_common_protobuf_toggle_proto_goTypes = nil
	file_common_protobuf_toggle_proto_depIdxs = nil
}
