// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.27.0
// source: common/protobuf/toggle.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListToggleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProjectId int64 `protobuf:"varint,1,opt,name=projectId,proto3" json:"projectId,omitempty"`
	Index     int64 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Size      int64 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *ListToggleRequest) Reset() {
	*x = ListToggleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_protobuf_toggle_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListToggleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListToggleRequest) ProtoMessage() {}

func (x *ListToggleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_protobuf_toggle_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListToggleRequest.ProtoReflect.Descriptor instead.
func (*ListToggleRequest) Descriptor() ([]byte, []int) {
	return file_common_protobuf_toggle_proto_rawDescGZIP(), []int{0}
}

func (x *ListToggleRequest) GetProjectId() int64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *ListToggleRequest) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ListToggleRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListToggleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total   int64             `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Toggles []*ListItemToggle `protobuf:"bytes,2,rep,name=toggles,proto3" json:"toggles,omitempty"`
}

func (x *ListToggleResponse) Reset() {
	*x = ListToggleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_protobuf_toggle_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListToggleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListToggleResponse) ProtoMessage() {}

func (x *ListToggleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_protobuf_toggle_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListToggleResponse.ProtoReflect.Descriptor instead.
func (*ListToggleResponse) Descriptor() ([]byte, []int) {
	return file_common_protobuf_toggle_proto_rawDescGZIP(), []int{1}
}

func (x *ListToggleResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListToggleResponse) GetToggles() []*ListItemToggle {
	if x != nil {
		return x.Toggles
	}
	return nil
}

type ListItemToggle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Enabled     bool   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Title       string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Key         string `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	Description string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	ValueType   string `protobuf:"bytes,6,opt,name=valueType,proto3" json:"valueType,omitempty"`
}

func (x *ListItemToggle) Reset() {
	*x = ListItemToggle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_protobuf_toggle_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListItemToggle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemToggle) ProtoMessage() {}

func (x *ListItemToggle) ProtoReflect() protoreflect.Message {
	mi := &file_common_protobuf_toggle_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemToggle.ProtoReflect.Descriptor instead.
func (*ListItemToggle) Descriptor() ([]byte, []int) {
	return file_common_protobuf_toggle_proto_rawDescGZIP(), []int{2}
}

func (x *ListItemToggle) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListItemToggle) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ListItemToggle) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ListItemToggle) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ListItemToggle) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ListItemToggle) GetValueType() string {
	if x != nil {
		return x.ValueType
	}
	return ""
}

type GetToggleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetToggleRequest) Reset() {
	*x = GetToggleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_protobuf_toggle_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetToggleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetToggleRequest) ProtoMessage() {}

func (x *GetToggleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_protobuf_toggle_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetToggleRequest.ProtoReflect.Descriptor instead.
func (*GetToggleRequest) Descriptor() ([]byte, []int) {
	return file_common_protobuf_toggle_proto_rawDescGZIP(), []int{3}
}

func (x *GetToggleRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Toggle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            int64          `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId     int64          `protobuf:"varint,2,opt,name=projectId,proto3" json:"projectId,omitempty"`
	ProjectKey    string         `protobuf:"bytes,3,opt,name=projectKey,proto3" json:"projectKey,omitempty"`
	Enabled       bool           `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Title         string         `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Key           string         `protobuf:"bytes,6,opt,name=key,proto3" json:"key,omitempty"`
	Description   string         `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	ValueType     string         `protobuf:"bytes,8,opt,name=valueType,proto3" json:"valueType,omitempty"`
	DefaultValue  int64          `protobuf:"varint,9,opt,name=defaultValue,proto3" json:"defaultValue,omitempty"`
	DisabledValue int64          `protobuf:"varint,10,opt,name=disabledValue,proto3" json:"disabledValue,omitempty"`
	CreateTime    int64          `protobuf:"varint,11,opt,name=createTime,proto3" json:"createTime,omitempty"`
	UpdateTime    int64          `protobuf:"varint,12,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	Values        []*ToggleValue `protobuf:"bytes,13,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *Toggle) Reset() {
	*x = Toggle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_protobuf_toggle_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Toggle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Toggle) ProtoMessage() {}

func (x *Toggle) ProtoReflect() protoreflect.Message {
	mi := &file_common_protobuf_toggle_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Toggle.ProtoReflect.Descriptor instead.
func (*Toggle) Descriptor() ([]byte, []int) {
	return file_common_protobuf_toggle_proto_rawDescGZIP(), []int{4}
}

func (x *Toggle) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Toggle) GetProjectId() int64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *Toggle) GetProjectKey() string {
	if x != nil {
		return x.ProjectKey
	}
	return ""
}

func (x *Toggle) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Toggle) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Toggle) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Toggle) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Toggle) GetValueType() string {
	if x != nil {
		return x.ValueType
	}
	return ""
}

func (x *Toggle) GetDefaultValue() int64 {
	if x != nil {
		return x.DefaultValue
	}
	return 0
}

func (x *Toggle) GetDisabledValue() int64 {
	if x != nil {
		return x.DisabledValue
	}
	return 0
}

func (x *Toggle) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *Toggle) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

func (x *Toggle) GetValues() []*ToggleValue {
	if x != nil {
		return x.Values
	}
	return nil
}

type ToggleValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ToggleId    int64  `protobuf:"varint,2,opt,name=toggleId,proto3" json:"toggleId,omitempty"`
	Title       string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Value       string `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Description string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	CreateTime  int64  `protobuf:"varint,6,opt,name=createTime,proto3" json:"createTime,omitempty"`
}

func (x *ToggleValue) Reset() {
	*x = ToggleValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_protobuf_toggle_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ToggleValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleValue) ProtoMessage() {}

func (x *ToggleValue) ProtoReflect() protoreflect.Message {
	mi := &file_common_protobuf_toggle_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleValue.ProtoReflect.Descriptor instead.
func (*ToggleValue) Descriptor() ([]byte, []int) {
	return file_common_protobuf_toggle_proto_rawDescGZIP(), []int{5}
}

func (x *ToggleValue) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ToggleValue) GetToggleId() int64 {
	if x != nil {
		return x.ToggleId
	}
	return 0
}

func (x *ToggleValue) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ToggleValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ToggleValue) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ToggleValue) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

type BoolToggleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReqUser    *ReqUser `protobuf:"bytes,1,opt,name=reqUser,proto3" json:"reqUser,omitempty"`
	ProjectKey string   `protobuf:"bytes,2,opt,name=projectKey,proto3" json:"projectKey,omitempty"`
	ToggleKey  string   `protobuf:"bytes,3,opt,name=toggleKey,proto3" json:"toggleKey,omitempty"`
}

func (x *BoolToggleRequest) Reset() {
	*x = BoolToggleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_protobuf_toggle_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BoolToggleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoolToggleRequest) ProtoMessage() {}

func (x *BoolToggleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_protobuf_toggle_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoolToggleRequest.ProtoReflect.Descriptor instead.
func (*BoolToggleRequest) Descriptor() ([]byte, []int) {
	return file_common_protobuf_toggle_proto_rawDescGZIP(), []int{6}
}

func (x *BoolToggleRequest) GetReqUser() *ReqUser {
	if x != nil {
		return x.ReqUser
	}
	return nil
}

func (x *BoolToggleRequest) GetProjectKey() string {
	if x != nil {
		return x.ProjectKey
	}
	return ""
}

func (x *BoolToggleRequest) GetToggleKey() string {
	if x != nil {
		return x.ToggleKey
	}
	return ""
}

type BoolToggleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ToggleKey   string `protobuf:"bytes,1,opt,name=toggleKey,proto3" json:"toggleKey,omitempty"`
	ResultValue bool   `protobuf:"varint,2,opt,name=resultValue,proto3" json:"resultValue,omitempty"`
}

func (x *BoolToggleResponse) Reset() {
	*x = BoolToggleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_protobuf_toggle_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BoolToggleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoolToggleResponse) ProtoMessage() {}

func (x *BoolToggleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_protobuf_toggle_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoolToggleResponse.ProtoReflect.Descriptor instead.
func (*BoolToggleResponse) Descriptor() ([]byte, []int) {
	return file_common_protobuf_toggle_proto_rawDescGZIP(), []int{7}
}

func (x *BoolToggleResponse) GetToggleKey() string {
	if x != nil {
		return x.ToggleKey
	}
	return ""
}

func (x *BoolToggleResponse) GetResultValue() bool {
	if x != nil {
		return x.ResultValue
	}
	return false
}

type StringToggleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReqUser    *ReqUser `protobuf:"bytes,1,opt,name=reqUser,proto3" json:"reqUser,omitempty"`
	ProjectKey string   `protobuf:"bytes,2,opt,name=projectKey,proto3" json:"projectKey,omitempty"`
	ToggleKey  string   `protobuf:"bytes,3,opt,name=toggleKey,proto3" json:"toggleKey,omitempty"`
}

func (x *StringToggleRequest) Reset() {
	*x = StringToggleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_protobuf_toggle_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StringToggleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringToggleRequest) ProtoMessage() {}

func (x *StringToggleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_protobuf_toggle_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringToggleRequest.ProtoReflect.Descriptor instead.
func (*StringToggleRequest) Descriptor() ([]byte, []int) {
	return file_common_protobuf_toggle_proto_rawDescGZIP(), []int{8}
}

func (x *StringToggleRequest) GetReqUser() *ReqUser {
	if x != nil {
		return x.ReqUser
	}
	return nil
}

func (x *StringToggleRequest) GetProjectKey() string {
	if x != nil {
		return x.ProjectKey
	}
	return ""
}

func (x *StringToggleRequest) GetToggleKey() string {
	if x != nil {
		return x.ToggleKey
	}
	return ""
}

type StringToggleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ToggleKey   string `protobuf:"bytes,1,opt,name=toggleKey,proto3" json:"toggleKey,omitempty"`
	ResultValue string `protobuf:"bytes,2,opt,name=resultValue,proto3" json:"resultValue,omitempty"`
}

func (x *StringToggleResponse) Reset() {
	*x = StringToggleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_protobuf_toggle_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StringToggleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringToggleResponse) ProtoMessage() {}

func (x *StringToggleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_protobuf_toggle_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringToggleResponse.ProtoReflect.Descriptor instead.
func (*StringToggleResponse) Descriptor() ([]byte, []int) {
	return file_common_protobuf_toggle_proto_rawDescGZIP(), []int{9}
}

func (x *StringToggleResponse) GetToggleKey() string {
	if x != nil {
		return x.ToggleKey
	}
	return ""
}

func (x *StringToggleResponse) GetResultValue() string {
	if x != nil {
		return x.ResultValue
	}
	return ""
}

type FloatToggleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReqUser    *ReqUser `protobuf:"bytes,1,opt,name=reqUser,proto3" json:"reqUser,omitempty"`
	ProjectKey string   `protobuf:"bytes,2,opt,name=projectKey,proto3" json:"projectKey,omitempty"`
	ToggleKey  string   `protobuf:"bytes,3,opt,name=toggleKey,proto3" json:"toggleKey,omitempty"`
}

func (x *FloatToggleRequest) Reset() {
	*x = FloatToggleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_protobuf_toggle_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FloatToggleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FloatToggleRequest) ProtoMessage() {}

func (x *FloatToggleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_protobuf_toggle_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FloatToggleRequest.ProtoReflect.Descriptor instead.
func (*FloatToggleRequest) Descriptor() ([]byte, []int) {
	return file_common_protobuf_toggle_proto_rawDescGZIP(), []int{10}
}

func (x *FloatToggleRequest) GetReqUser() *ReqUser {
	if x != nil {
		return x.ReqUser
	}
	return nil
}

func (x *FloatToggleRequest) GetProjectKey() string {
	if x != nil {
		return x.ProjectKey
	}
	return ""
}

func (x *FloatToggleRequest) GetToggleKey() string {
	if x != nil {
		return x.ToggleKey
	}
	return ""
}

type FloatToggleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ToggleKey   string  `protobuf:"bytes,1,opt,name=toggleKey,proto3" json:"toggleKey,omitempty"`
	ResultValue float32 `protobuf:"fixed32,2,opt,name=resultValue,proto3" json:"resultValue,omitempty"`
}

func (x *FloatToggleResponse) Reset() {
	*x = FloatToggleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_protobuf_toggle_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FloatToggleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FloatToggleResponse) ProtoMessage() {}

func (x *FloatToggleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_protobuf_toggle_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FloatToggleResponse.ProtoReflect.Descriptor instead.
func (*FloatToggleResponse) Descriptor() ([]byte, []int) {
	return file_common_protobuf_toggle_proto_rawDescGZIP(), []int{11}
}

func (x *FloatToggleResponse) GetToggleKey() string {
	if x != nil {
		return x.ToggleKey
	}
	return ""
}

func (x *FloatToggleResponse) GetResultValue() float32 {
	if x != nil {
		return x.ResultValue
	}
	return 0
}

type IntToggleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReqUser    *ReqUser `protobuf:"bytes,1,opt,name=reqUser,proto3" json:"reqUser,omitempty"`
	ProjectKey string   `protobuf:"bytes,2,opt,name=projectKey,proto3" json:"projectKey,omitempty"`
	ToggleKey  string   `protobuf:"bytes,3,opt,name=toggleKey,proto3" json:"toggleKey,omitempty"`
}

func (x *IntToggleRequest) Reset() {
	*x = IntToggleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_protobuf_toggle_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IntToggleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntToggleRequest) ProtoMessage() {}

func (x *IntToggleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_protobuf_toggle_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntToggleRequest.ProtoReflect.Descriptor instead.
func (*IntToggleRequest) Descriptor() ([]byte, []int) {
	return file_common_protobuf_toggle_proto_rawDescGZIP(), []int{12}
}

func (x *IntToggleRequest) GetReqUser() *ReqUser {
	if x != nil {
		return x.ReqUser
	}
	return nil
}

func (x *IntToggleRequest) GetProjectKey() string {
	if x != nil {
		return x.ProjectKey
	}
	return ""
}

func (x *IntToggleRequest) GetToggleKey() string {
	if x != nil {
		return x.ToggleKey
	}
	return ""
}

type IntToggleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ToggleKey   string `protobuf:"bytes,1,opt,name=toggleKey,proto3" json:"toggleKey,omitempty"`
	ResultValue int64  `protobuf:"varint,2,opt,name=resultValue,proto3" json:"resultValue,omitempty"`
}

func (x *IntToggleResponse) Reset() {
	*x = IntToggleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_protobuf_toggle_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IntToggleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntToggleResponse) ProtoMessage() {}

func (x *IntToggleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_protobuf_toggle_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntToggleResponse.ProtoReflect.Descriptor instead.
func (*IntToggleResponse) Descriptor() ([]byte, []int) {
	return file_common_protobuf_toggle_proto_rawDescGZIP(), []int{13}
}

func (x *IntToggleResponse) GetToggleKey() string {
	if x != nil {
		return x.ToggleKey
	}
	return ""
}

func (x *IntToggleResponse) GetResultValue() int64 {
	if x != nil {
		return x.ResultValue
	}
	return 0
}

type JsonToggleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReqUser    *ReqUser `protobuf:"bytes,1,opt,name=reqUser,proto3" json:"reqUser,omitempty"`
	ProjectKey string   `protobuf:"bytes,2,opt,name=projectKey,proto3" json:"projectKey,omitempty"`
	ToggleKey  string   `protobuf:"bytes,3,opt,name=toggleKey,proto3" json:"toggleKey,omitempty"`
}

func (x *JsonToggleRequest) Reset() {
	*x = JsonToggleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_protobuf_toggle_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JsonToggleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsonToggleRequest) ProtoMessage() {}

func (x *JsonToggleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_protobuf_toggle_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsonToggleRequest.ProtoReflect.Descriptor instead.
func (*JsonToggleRequest) Descriptor() ([]byte, []int) {
	return file_common_protobuf_toggle_proto_rawDescGZIP(), []int{14}
}

func (x *JsonToggleRequest) GetReqUser() *ReqUser {
	if x != nil {
		return x.ReqUser
	}
	return nil
}

func (x *JsonToggleRequest) GetProjectKey() string {
	if x != nil {
		return x.ProjectKey
	}
	return ""
}

func (x *JsonToggleRequest) GetToggleKey() string {
	if x != nil {
		return x.ToggleKey
	}
	return ""
}

type JsonToggleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ToggleKey   string `protobuf:"bytes,1,opt,name=toggleKey,proto3" json:"toggleKey,omitempty"`
	ResultValue string `protobuf:"bytes,2,opt,name=resultValue,proto3" json:"resultValue,omitempty"`
}

func (x *JsonToggleResponse) Reset() {
	*x = JsonToggleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_protobuf_toggle_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JsonToggleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsonToggleResponse) ProtoMessage() {}

func (x *JsonToggleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_protobuf_toggle_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsonToggleResponse.ProtoReflect.Descriptor instead.
func (*JsonToggleResponse) Descriptor() ([]byte, []int) {
	return file_common_protobuf_toggle_proto_rawDescGZIP(), []int{15}
}

func (x *JsonToggleResponse) GetToggleKey() string {
	if x != nil {
		return x.ToggleKey
	}
	return ""
}

func (x *JsonToggleResponse) GetResultValue() string {
	if x != nil {
		return x.ResultValue
	}
	return ""
}

type ReqUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RolloutKey string            `protobuf:"bytes,1,opt,name=rolloutKey,proto3" json:"rolloutKey,omitempty"`
	Attributes map[string]string `protobuf:"bytes,2,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *ReqUser) Reset() {
	*x = ReqUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_protobuf_toggle_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqUser) ProtoMessage() {}

func (x *ReqUser) ProtoReflect() protoreflect.Message {
	mi := &file_common_protobuf_toggle_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqUser.ProtoReflect.Descriptor instead.
func (*ReqUser) Descriptor() ([]byte, []int) {
	return file_common_protobuf_toggle_proto_rawDescGZIP(), []int{16}
}

func (x *ReqUser) GetRolloutKey() string {
	if x != nil {
		return x.RolloutKey
	}
	return ""
}

func (x *ReqUser) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

var File_common_protobuf_toggle_proto protoreflect.FileDescriptor

var file_common_protobuf_toggle_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x74, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5b,
	0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0x55, 0x0a, 0x12, 0x4c,
	0x69, 0x73, 0x74, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x29, 0x0a, 0x07, 0x74, 0x6f, 0x67, 0x67, 0x6c,
	0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x49,
	0x74, 0x65, 0x6d, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x52, 0x07, 0x74, 0x6f, 0x67, 0x67, 0x6c,
	0x65, 0x73, 0x22, 0xa2, 0x01, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x54,
	0x6f, 0x67, 0x67, 0x6c, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x54, 0x79, 0x70, 0x65, 0x22, 0x22, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x54, 0x6f,
	0x67, 0x67, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x88, 0x03, 0x0a, 0x06,
	0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63,
	0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x6a, 0x65,
	0x63, 0x74, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x4b,
	0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63,
	0x74, 0x4b, 0x65, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c,
	0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x64, 0x65,
	0x66, 0x61, 0x75, 0x6c, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x64, 0x69,
	0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0d, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x0b,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x1e, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x0c,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x24, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x0d, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x06,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0xa7, 0x01, 0x0a, 0x0b, 0x54, 0x6f, 0x67, 0x67, 0x6c,
	0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x6f, 0x67, 0x67, 0x6c, 0x65,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x74, 0x6f, 0x67, 0x67, 0x6c, 0x65,
	0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x20,
	0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x22, 0x75, 0x0a, 0x11, 0x42, 0x6f, 0x6f, 0x6c, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x55, 0x73, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x52, 0x65, 0x71, 0x55, 0x73, 0x65, 0x72,
	0x52, 0x07, 0x72, 0x65, 0x71, 0x55, 0x73, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x72, 0x6f,
	0x6a, 0x65, 0x63, 0x74, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70,
	0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x4b, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x6f, 0x67,
	0x67, 0x6c, 0x65, 0x4b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x6f,
	0x67, 0x67, 0x6c, 0x65, 0x4b, 0x65, 0x79, 0x22, 0x54, 0x0a, 0x12, 0x42, 0x6f, 0x6f, 0x6c, 0x54,
	0x6f, 0x67, 0x67, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x74, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x74, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0b, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x77, 0x0a,
	0x13, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x55, 0x73, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x52, 0x65, 0x71, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x07, 0x72, 0x65, 0x71, 0x55, 0x73, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x6a,
	0x65, 0x63, 0x74, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72,
	0x6f, 0x6a, 0x65, 0x63, 0x74, 0x4b, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x6f, 0x67, 0x67,
	0x6c, 0x65, 0x4b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x6f, 0x67,
	0x67, 0x6c, 0x65, 0x4b, 0x65, 0x79, 0x22, 0x56, 0x0a, 0x14, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67,
	0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x74, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x74, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x20, 0x0a, 0x0b,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x76,
	0x0a, 0x12, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x55, 0x73, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x52, 0x65, 0x71, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x07, 0x72, 0x65, 0x71, 0x55, 0x73, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x6a,
	0x65, 0x63, 0x74, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72,
	0x6f, 0x6a, 0x65, 0x63, 0x74, 0x4b, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x6f, 0x67, 0x67,
	0x6c, 0x65, 0x4b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x6f, 0x67,
	0x67, 0x6c, 0x65, 0x4b, 0x65, 0x79, 0x22, 0x55, 0x0a, 0x13, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x54,
	0x6f, 0x67, 0x67, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x74, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x74, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x0b, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x74, 0x0a,
	0x10, 0x49, 0x6e, 0x74, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x22, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x55, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x08, 0x2e, 0x52, 0x65, 0x71, 0x55, 0x73, 0x65, 0x72, 0x52, 0x07, 0x72, 0x65,
	0x71, 0x55, 0x73, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74,
	0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x6a, 0x65,
	0x63, 0x74, 0x4b, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x4b,
	0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x6f, 0x67, 0x67, 0x6c, 0x65,
	0x4b, 0x65, 0x79, 0x22, 0x53, 0x0a, 0x11, 0x49, 0x6e, 0x74, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x6f, 0x67, 0x67,
	0x6c, 0x65, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x6f, 0x67,
	0x67, 0x6c, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x75, 0x0a, 0x11, 0x4a, 0x73, 0x6f, 0x6e,
	0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a,
	0x07, 0x72, 0x65, 0x71, 0x55, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08,
	0x2e, 0x52, 0x65, 0x71, 0x55, 0x73, 0x65, 0x72, 0x52, 0x07, 0x72, 0x65, 0x71, 0x55, 0x73, 0x65,
	0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x4b, 0x65, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x4b, 0x65,
	0x79, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x4b, 0x65, 0x79, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x4b, 0x65, 0x79, 0x22,
	0x54, 0x0a, 0x12, 0x4a, 0x73, 0x6f, 0x6e, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x4b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x6f, 0x67, 0x67, 0x6c, 0x65,
	0x4b, 0x65, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0xa2, 0x01, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x55, 0x73, 0x65,
	0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x6f, 0x6c, 0x6c, 0x6f, 0x75, 0x74, 0x4b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x6f, 0x6c, 0x6c, 0x6f, 0x75, 0x74, 0x4b, 0x65,
	0x79, 0x12, 0x38, 0x0a, 0x0a, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x52, 0x65, 0x71, 0x55, 0x73, 0x65, 0x72, 0x2e,
	0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x0a, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x1a, 0x3d, 0x0a, 0x0f, 0x41,
	0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x32, 0x97, 0x03, 0x0a, 0x0d, 0x54,
	0x6f, 0x67, 0x67, 0x6c, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x35, 0x0a, 0x0a,
	0x4c, 0x69, 0x73, 0x74, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x12, 0x12, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65,
	0x12, 0x11, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x07, 0x2e, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x12, 0x38, 0x0a, 0x0d,
	0x47, 0x65, 0x74, 0x42, 0x6f, 0x6f, 0x6c, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x12, 0x12, 0x2e,
	0x42, 0x6f, 0x6f, 0x6c, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x13, 0x2e, 0x42, 0x6f, 0x6f, 0x6c, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x53, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x12, 0x14, 0x2e, 0x53, 0x74, 0x72, 0x69,
	0x6e, 0x67, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x15, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x46, 0x6c, 0x6f,
	0x61, 0x74, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x12, 0x13, 0x2e, 0x46, 0x6c, 0x6f, 0x61, 0x74,
	0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e,
	0x46, 0x6c, 0x6f, 0x61, 0x74, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x74, 0x54, 0x6f, 0x67,
	0x67, 0x6c, 0x65, 0x12, 0x11, 0x2e, 0x49, 0x6e, 0x74, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x49, 0x6e, 0x74, 0x54, 0x6f, 0x67, 0x67,
	0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x0d, 0x47, 0x65,
	0x74, 0x4a, 0x73, 0x6f, 0x6e, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x12, 0x12, 0x2e, 0x4a, 0x73,
	0x6f, 0x6e, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x13, 0x2e, 0x4a, 0x73, 0x6f, 0x6e, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_protobuf_toggle_proto_rawDescOnce sync.Once
	file_common_protobuf_toggle_proto_rawDescData = file_common_protobuf_toggle_proto_rawDesc
)

func file_common_protobuf_toggle_proto_rawDescGZIP() []byte {
	file_common_protobuf_toggle_proto_rawDescOnce.Do(func() {
		file_common_protobuf_toggle_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_protobuf_toggle_proto_rawDescData)
	})
	return file_common_protobuf_toggle_proto_rawDescData
}

var file_common_protobuf_toggle_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_common_protobuf_toggle_proto_goTypes = []interface{}{
	(*ListToggleRequest)(nil),    // 0: ListToggleRequest
	(*ListToggleResponse)(nil),   // 1: ListToggleResponse
	(*ListItemToggle)(nil),       // 2: ListItemToggle
	(*GetToggleRequest)(nil),     // 3: GetToggleRequest
	(*Toggle)(nil),               // 4: Toggle
	(*ToggleValue)(nil),          // 5: ToggleValue
	(*BoolToggleRequest)(nil),    // 6: BoolToggleRequest
	(*BoolToggleResponse)(nil),   // 7: BoolToggleResponse
	(*StringToggleRequest)(nil),  // 8: StringToggleRequest
	(*StringToggleResponse)(nil), // 9: StringToggleResponse
	(*FloatToggleRequest)(nil),   // 10: FloatToggleRequest
	(*FloatToggleResponse)(nil),  // 11: FloatToggleResponse
	(*IntToggleRequest)(nil),     // 12: IntToggleRequest
	(*IntToggleResponse)(nil),    // 13: IntToggleResponse
	(*JsonToggleRequest)(nil),    // 14: JsonToggleRequest
	(*JsonToggleResponse)(nil),   // 15: JsonToggleResponse
	(*ReqUser)(nil),              // 16: ReqUser
	nil,                          // 17: ReqUser.AttributesEntry
}
var file_common_protobuf_toggle_proto_depIdxs = []int32{
	2,  // 0: ListToggleResponse.toggles:type_name -> ListItemToggle
	5,  // 1: Toggle.values:type_name -> ToggleValue
	16, // 2: BoolToggleRequest.reqUser:type_name -> ReqUser
	16, // 3: StringToggleRequest.reqUser:type_name -> ReqUser
	16, // 4: FloatToggleRequest.reqUser:type_name -> ReqUser
	16, // 5: IntToggleRequest.reqUser:type_name -> ReqUser
	16, // 6: JsonToggleRequest.reqUser:type_name -> ReqUser
	17, // 7: ReqUser.attributes:type_name -> ReqUser.AttributesEntry
	0,  // 8: ToggleService.ListToggle:input_type -> ListToggleRequest
	3,  // 9: ToggleService.GetToggle:input_type -> GetToggleRequest
	6,  // 10: ToggleService.GetBoolToggle:input_type -> BoolToggleRequest
	8,  // 11: ToggleService.GetStringToggle:input_type -> StringToggleRequest
	10, // 12: ToggleService.GetFloatToggle:input_type -> FloatToggleRequest
	12, // 13: ToggleService.GetIntToggle:input_type -> IntToggleRequest
	14, // 14: ToggleService.GetJsonToggle:input_type -> JsonToggleRequest
	1,  // 15: ToggleService.ListToggle:output_type -> ListToggleResponse
	4,  // 16: ToggleService.GetToggle:output_type -> Toggle
	7,  // 17: ToggleService.GetBoolToggle:output_type -> BoolToggleResponse
	9,  // 18: ToggleService.GetStringToggle:output_type -> StringToggleResponse
	11, // 19: ToggleService.GetFloatToggle:output_type -> FloatToggleResponse
	13, // 20: ToggleService.GetIntToggle:output_type -> IntToggleResponse
	15, // 21: ToggleService.GetJsonToggle:output_type -> JsonToggleResponse
	15, // [15:22] is the sub-list for method output_type
	8,  // [8:15] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_common_protobuf_toggle_proto_init() }
func file_common_protobuf_toggle_proto_init() {
	if File_common_protobuf_toggle_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_protobuf_toggle_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListToggleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_protobuf_toggle_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListToggleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_protobuf_toggle_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListItemToggle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_protobuf_toggle_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetToggleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_protobuf_toggle_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Toggle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_protobuf_toggle_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ToggleValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_protobuf_toggle_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BoolToggleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_protobuf_toggle_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BoolToggleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_protobuf_toggle_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StringToggleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_protobuf_toggle_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StringToggleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_protobuf_toggle_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FloatToggleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_protobuf_toggle_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FloatToggleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_protobuf_toggle_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IntToggleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_protobuf_toggle_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IntToggleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_protobuf_toggle_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JsonToggleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_protobuf_toggle_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JsonToggleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_protobuf_toggle_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_protobuf_toggle_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_common_protobuf_toggle_proto_goTypes,
		DependencyIndexes: file_common_protobuf_toggle_proto_depIdxs,
		MessageInfos:      file_common_protobuf_toggle_proto_msgTypes,
	}.Build()
	File_common_protobuf_toggle_proto = out.File
	file_common_protobuf_toggle_proto_rawDesc = nil
	file_common_protobuf_toggle_proto_goTypes = nil
	file_common_protobuf_toggle_proto_depIdxs = nil
}
